### ISSUE TITLE
Spawning swarm workers using cron

### ISSUE THREAD

**Issue by kabamwboyer** [ambakshi/docker-perforce#13]
Hey, @ambakshi ! Thank you for your excellent work on this project... I have used it as the basis for creating a test environment, but am struggling to get the cron job to spawn workers on the Helix Swarm server to work, which I wrote about in [this SuperUser post](https://superuser.com/questions/1443166/helix-swarm-2018-2-in-docker-container-cant-spawn-workers)... Would you be willing to lend me your insight, seeing as I don't see how this project accounts for this setup step? Thank you so much!

**Comment by kabamwboyer** [comment]
This is actually somewhat related to #11 because I managed to get crond working, but the swarm-cron.sh seems to be busted!

**Comment by ambakshi** [comment]
Hey, I think I've fixed all those issues. Please give it another try. crond and systemctl should be working now. Thanks!
