### ISSUE TITLE
[Errno -1] repomd.xml does not match metalink for epel Trying other mirror.

### ISSUE THREAD

**Issue by yanghansyuan** [ambakshi/docker-perforce#15]
Hi, 
I try to build docker for the perforce-server nad got the error when determining fastest mirrors:

> http://fedora.cs.nctu.edu.tw/epel/7/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for epel
> Trying other mirror.

> The command '/bin/sh -c yum clean all --enablerepo='*'     && yum clean metadata --enablerepo='*'     && yum install --enablerepo=perforce -y helix-p4d-20${P4_VERSION} helix-cli-20${P4_VERSION}     && yum clean all --enablerepo='*'     && rm -rf /var/cache/yum' returned a non-zero code: 1

How do I fix this?  I'm using Mac.  Thank you

**Comment by Laughlete** [comment]
I'm seeing the same issue, running Docker on Windows 10 Pro.

**Comment by Laughlete** [comment]
On my computer I didn't have the env var P4_VERSION set.

I replaced the line 

`&& yum install --enablerepo=perforce -y helix-p4d-20${P4_VERSION} helix-cli-20${P4_VERSION} \`
with
`&& yum install --enablerepo=perforce -y helix-p4d-2019.1 helix-cli-2019.1 \`

and then it worked.

**Comment by yanghansyuan** [comment]
Thank you. It works!

**Comment by ambakshi** [comment]
The Makefile sets it. So either you need to use `make` or as @Laughlete mentioned, set the env var.
