### ISSUE TITLE
what is the init password of p4admin account

### ISSUE THREAD

**Issue by FashGek** [ambakshi/docker-perforce#17]
i connecnt to the docker perfoce server with p4 client, when login with the p4admin account, but i don't know the accout?what is the $P4PASSSWD

**Comment by HaberkornJonas** [comment]
I belive it should be "pass12349ers!" as defined in the [/perforce-server/setup-perforce.sh](https://github.com/ambakshi/docker-perforce/blob/1fc57e2c90454bfaf3c5b293da2fc4aae502342d/perforce-server/setup-perforce.sh#L18) and [/envfile](https://github.com/ambakshi/docker-perforce/blob/1fc57e2c90454bfaf3c5b293da2fc4aae502342d/envfile#L4) files.

**Comment by FashGek** [comment]
> I belive it should be "pass12349ers!" as defined in the [/perforce-server/setup-perforce.sh](https://github.com/ambakshi/docker-perforce/blob/1fc57e2c90454bfaf3c5b293da2fc4aae502342d/perforce-server/setup-perforce.sh#L18) and [/envfile](https://github.com/ambakshi/docker-perforce/blob/1fc57e2c90454bfaf3c5b293da2fc4aae502342d/envfile#L4) files.

thankypu very much
